version: '3'
services:
  deployment:
    mem_limit: 6144M
    mem_reservation: 2048M
    cpus: 1.5
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '80:8080'
      - '443:8080'